regression_metric:
  class_path: comet.models.RegressionMetric
  init_args:
    nr_frozen_epochs: 0.3
    keep_embeddings_frozen: True
    optimizer: AdamW
    encoder_learning_rate: 1.0e-05
    learning_rate: 3.1e-05
    layerwise_decay: 0.95
    encoder_model: MiniLM
    pretrained_model: microsoft/Multilingual-MiniLM-L12-H384
    pool: avg
    layer: mix
    dropout: 0.15
    batch_size: 8
    train_data: data/TRAIN.csv
    validation_data: data/DEV.csv
    hidden_sizes:
      - 384
    
trainer: ../trainer.yaml
early_stopping: ../early_stopping.yaml
model_checkpoint: ../model_checkpoint.yaml